site_name: Test Iaso docs
# Add Edit on Github button
repo_url: https://github.com/quang-le/mkDocs-test
edit_uri: edit/main/docs/
extra_javascript: 
  - button.js
theme:
  name: readthedocs
  navigation_depth: 6
  highlightjs: true
  theme_dir: overrides
plugins:
    - awesome-pages:
        collapse_single_pages: true
    - search
    - mermaid2
    - i18n:
        docs_structure: suffix
        default_language: en
        languages:
          default: Default (EN)
          en:
            name: English
            site_name: Iaso docs in English
          fr: 
            name: Français
            site_name: Page en français
        nav_translations:
          fr:
            Home: Accueil
            How to: Guides
            Deploy: Déployer
            MORE: PLUS
            FAQ: POUF
            Audit: Inspection
nav:
  - Home: index.md
  - How to:
      - Deploy: how_to_deploy.md
      - Use the APIs: how_to_use_iaso_s_api.md
      - Contribute: contributing.md

  - References:
    - Development environment: development_environment.md
    - Data model glossary: data_model_glossary.md
    - Enketo: enketo.md
    - Audit: audit.md
    - Front-end assets: front_end_assets.md
    - Vector control: vector_control.md
  - MORE:
    - About Iaso: about_iaso.md
    - Full README: iaso_readme_full.md
    - Source code: https://github.com/BLSQ/iaso
  - FAQ: 
      - That one question: FAQ.md